# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "boxomatic/centos-7"

  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "sunparkS" do |control|
    control.vm.hostname = "sunparkS"
    control.vm.network "private_network", ip: "192.168.56.110"

    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "sunparkS"]
    end

    control.vm.provision "shell", inline: <<-SHELL
    curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --cluster-init --node-ip="192.168.56.110"
    sed 's/<app-name>/app-one/g' /vagrant/confs/app-template.yaml | /usr/local/bin/kubectl apply -f -
    sed 's/<app-name>/app-two/g' /vagrant/confs/app-template.yaml | sed 's/replicas: 1/replicas: 3/g' | /usr/local/bin/kubectl apply -f -
    sed 's/<app-name>/app-three/g' /vagrant/confs/app-template.yaml | /usr/local/bin/kubectl apply -f -
    /usr/local/bin/kubectl apply -f /vagrant/confs/traefik.yaml
    SHELL

  end
end
 