# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "boxomatic/centos-7"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define "sunparkS" do |control|
    control.vm.hostname = "sunparkS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "sunparkS"]
    end
    control.vm.provision "shell", inline: <<-SHELL
    curl -sfL https://get.k3s.io/ | sh -s - --cluster-init --node-ip=192.168.56.110 --write-kubeconfig-mode 644
    sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/confs/node-token
    SHELL
  end

  config.vm.define "sunparkSW" do |control|
    control.vm.hostname = "sunparkSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "sunparkSW"]
    end
    control.vm.provision "shell", inline: <<-SHELL
    curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$(cat /vagrant/confs/node-token) sh -s - --node-ip=192.168.56.111
    rm /vagrant/confs/node-token
    SHELL
  end
end
 