# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "boxomatic/centos-7"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.define "sunparkS" do |control|
    control.vm.hostname = "sunparkS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.network "forwarded_port", guest: 8080, host: 8081
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "sunparkS"]
    end
  end
end
 